apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Release.Name }}-stage"
  labels:
    env: "{{ .Release.Name }}-stage"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
