image:
  repository: ropelive/countbase
  tag: 1.0.0
  pullPolicy: IfNotPresent

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images

appName: "counter"
mongodbURL: mongodb://rope_admin:minda@stage-mongodb-mongodb:27017/rope
redisURL: stage-redis-redis:6379

## Kubernetes service type
serviceType: NodePort

port: 8080

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 100m

# self-update to the latest release version
keel:
  policy: all # (all/major/minor/patch/force)
  trigger: poll
  approvals: 0
  pollSchedule: "@every 1m"
  images:
   - repository: image.repository
     tag: image.tag
