image:
  repository: ropelive/twine
  tag: 1.0.2
  pullPolicy: IfNotPresent

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images

redisURL: redis://redis-redis:6379
secret: "my_super_awesome_secret"

## Kubernetes service type
serviceType: NodePort

port: 4000

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 100m

# self-update to the latest release version
keel:
  policy: all # (all/major/minor/patch/force)
  trigger: poll
  approvals: 0
  pollSchedule: "@every 1m"
  images:
   - repository: image.repository
     tag: image.tag
