apiVersion: v1
kind: Secret
metadata:
  name: {{ template "twine.fullname" . }}
  labels:
    app: {{ template "twine.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  redis-url: {{  default "" .Values.redisURL | b64enc | quote }}
  twine-secret: {{  default "" .Values.twineSecret | b64enc | quote }}
