apiVersion: v1
kind: Service
metadata:
  name: {{ template "twine.fullname" . }}
  labels:
    app: {{ template "twine.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  selector:
    app: {{ template "twine.fullname" . }}
