apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "count.fullname" . }}
  labels:
    app: {{ template "count.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "count.fullname" . }}
    spec:
      containers:
        - name: {{ template "count.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
          command:
            - "/go/bin/{{ .Values.appName }}" 
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "count.fullname" . }}
                  key: mongodb-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "count.fullname" . }}
                  key: redis-url
            - name: HTTP_ADDR
              value: ":{{ .Values.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.port }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.port }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
