apiVersion: v1
kind: Secret
metadata:
  name: {{ template "count.fullname" . }}
  labels:
    app: {{ template "count.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  mongodb-url: {{  default "" .Values.mongodbURL | b64enc | quote }}
  redis-url:   {{  default "" .Values.redisURL | b64enc | quote }}
